// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpezgxrwaykwvvvddkry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZXpneHJ3YXlrd3Z2dmRka3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDk3NzYsImV4cCI6MjA2NzI4NTc3Nn0.0XuS9HmoXcWKGUJKehU9Ku3sLAfdxdTT7iUSDEnx8JA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});